In [1]:
import numpy as np

# Task 1: Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)
print("Original vector:", random_vector)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)
print("Reshaped array:\n", reshaped_array)

# Print array shape
print("Array shape:", reshaped_array.shape)

# Replace the max in each row by 0
for row in reshaped_array:
    row[row.argmax()] = 0
print("Array with max replaced by 0:\n", reshaped_array)

# Task 2: Create a 2-dimensional array of size 4x3 with 4-byte integer elements
two_dim_array = np.array(np.random.randint(1, 21, size=(4, 3)), dtype='int32')
print("2-dimensional array:\n", two_dim_array)

# Print the shape, type, and data type of the array
print("Shape of the array:", two_dim_array.shape)
print("Type of the array:", type(two_dim_array))
print("Data type of the array:", two_dim_array.dtype)


Original vector: [15  2  3  6 11  7  8 10  6  4  3  3  6 15 14]
Reshaped array:
 [[15  2  3  6 11]
 [ 7  8 10  6  4]
 [ 3  3  6 15 14]]
Array shape: (3, 5)
Array with max replaced by 0:
 [[ 0  2  3  6 11]
 [ 7  8  0  6  4]
 [ 3  3  6  0 14]]
2-dimensional array:
 [[12  9  5]
 [ 1 19  2]
 [16  8  8]
 [ 7  4 13]]
Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [2]:
import numpy as np

# Given square array
A = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues of the array:\n", eigenvalues)
print("Right eigenvectors of the array:\n", eigenvectors)


Eigenvalues of the array:
 [2. 1.]
Right eigenvectors of the array:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [3]:
import numpy as np

# Given array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
# Since the given array is not square, we need to calculate the sum manually
diagonal_sum = np.sum(np.diag(array))
print("Sum of the diagonal elements:", diagonal_sum)


Sum of the diagonal elements: 4


In [4]:
import numpy as np

# Original array
original_array = np.array([[1, 2], [3, 4], [5, 6]])
print("Original array (3x2):\n", original_array)

# Reshape to 2x3
reshaped_array = original_array.reshape(2, 3)
print("Reshaped array (2x3):\n", reshaped_array)


Original array (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
